In [74]:
import pandas as pd

In [75]:
df = pd.read_csv('Enterprise Clients.csv')
df2 = pd.read_csv('enterprise_domain(closed_pay_380)_enriched.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [76]:
print(df['email'].nunique())

5243

In [77]:
df_active = df[df['subscription_status'] == 'Cancelled']
print(len(df_active))

3378

In [78]:
df_active['Pay'].dtypes

dtype('float64')

In [79]:
df_active_pay = df_active[df_active['Pay']>380]
print(len(df_active_pay))

103

In [80]:
df_active_pay = df_active_pay.copy()
df_active_pay['email'] = df_active_pay['email'].str.lower().str.strip()
df_active_pay = df_active_pay[~df_active_pay['email'].str.contains(' ', na=False)]
df_active_pay = df_active_pay.reset_index(drop=True)
print(len(df_active_pay))

103

In [81]:
df_active_pay[['username', 'domain']] = df_active_pay['email'].str.split('@', expand=True)
df_active_pay.head(2)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep,username,domain
0,abaoking668899@adeccoeu.com,Standard-Plan-Monthly-USD-Monthly,Cancelled,1951.75,0.0,1951.75,14,2,0.0,0.0,0.0,0,0,abaoking668899,adeccoeu.com
1,abdul.a@finplexsolution.com,Standard-Plan-Monthly-USD-Monthly,Cancelled,879.79,79.0,800.79,16,4,0.0,0.0,0.0,0,0,abdul.a,finplexsolution.com

In [82]:
final_df = df_active_pay[['email', 'domain']]
final_df = final_df.drop_duplicates(subset='domain')
final_df

                                        email                         domain
0                 abaoking668899@adeccoeu.com                   adeccoeu.com
1                 abdul.a@finplexsolution.com            finplexsolution.com
2                    abhishek@ppnsolutions.co                ppnsolutions.co
3                   adeola@creatify.solutions             creatify.solutions
4                          admin4@chinh.store                    chinh.store
..                                        ...                            ...
98                         troy@realty.com.au                  realty.com.au
99   truepower1@twofourteenenergyservices.com  twofourteenenergyservices.com
100                        ufinity@ufinity.in                     ufinity.in
101                          vu@debankero.com                  debankero.com
102                       william@movimak.net                    movimak.net

[103 rows x 2 columns]

In [83]:
final_df.to_csv('enterprise_domain(closed_pay_380).csv', index = False)

In [ ]:
final = pd.merge(df_active_pay, df2, on = ['email','domain'], how = 'left')
print(len(final))
final.head(5)

103

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,...,domain_x,domain_y,category,company_size,email_provider,confidence,other_industry_category,website,website_status,website_reason
0,abaoking668899@adeccoeu.com,Standard-Plan-Monthly-USD-Monthly,Cancelled,1951.75,0.0,1951.75,14,2,0.0,0.0,...,adeccoeu.com,adeccoeu.com,Professional Services,500+,No,60,NaN,little_info,reachable,200
1,abdul.a@finplexsolution.com,Standard-Plan-Monthly-USD-Monthly,Cancelled,879.79,79.0,800.79,16,4,0.0,0.0,...,finplexsolution.com,finplexsolution.com,Professional Services,50 to 100,No,95,NaN,much_info,reachable,200
2,abhishek@ppnsolutions.co,Essential-Plan-Monthly-USD-Monthly,Cancelled,1142.50,0.0,1142.50,5,0,66.0,0.0,...,ppnsolutions.co,ppnsolutions.co,Professional Services,5 to 20,No,70,NaN,unreachable,unreachable,Timeout
3,adeola@creatify.solutions,Essential-Plan-Monthly-USD-Monthly,Cancelled,804.32,0.0,804.32,107,0,0.0,0.0,...,creatify.solutions,creatify.solutions,Marketing and Advertising,1 to 5,No,95,NaN,much_info,reachable,200
4,admin4@chinh.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,1897.87,0.0,1897.87,6,1,0.0,0.0,...,chinh.store,chinh.store,Other,solo,No,95,Author/Literary Services,much_info,reachable,200

In [85]:
final = final.to_csv('closed_pay_380_domain_classify.csv', index = False)