In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('Enterprise Clients.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [21]:
print(df['email'].nunique())

5243

In [22]:
df_active = df[df['subscription_status'] == 'Active']
print(len(df_active))

1780

In [23]:
df_active['Pay'].dtypes

dtype('float64')

In [24]:
df_active_pay = df_active[df_active['Pay']>900]
print(len(df_active_pay))

107

In [25]:
final_df = df_active_pay.copy()
final_df['email'] = final_df['email'].str.lower().str.strip()
final_df = final_df[~final_df['email'].str.contains(' ', na=False)]
final_df = final_df.reset_index(drop=True)
print(len(final_df))

107

In [26]:
final_df[['username', 'domain']] = final_df['email'].str.split('@', expand=True)
final_df = final_df.drop_duplicates(subset='domain')
final_df = final_df[['domain']]
final_df

                           domain
0         infinitesolutionedu.com
1            buildtechnics.com.au
2    premiumplusproperties.com.au
3                      specfx.com
4                andromarkets.com
..                            ...
102                    eliptis.se
103                      msxi.com
104              retailinsight.io
105                       xebo.ai
106                    lsports.eu

[107 rows x 1 columns]

In [27]:
final_df.to_csv('enterprise_domain(active_pay_900).csv', index = False)