In [83]:
import pandas as pd

In [84]:
df = pd.read_csv('Enterprise Clients.csv')
df2 = pd.read_csv('enterprise_domain(active_pay_400_550)_enriched.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [85]:
print(df['email'].nunique())

5243

In [86]:
df_active = df[df['subscription_status'] == 'Active']
print(len(df_active))

1780

In [87]:
df_active['Pay'].dtypes

dtype('float64')

In [88]:
df_active_pay = df_active[df_active['Pay'].between(400,550)]
print(len(df_active_pay))

111

In [89]:
df_active_pay = df_active_pay.copy()
df_active_pay['email'] = df_active_pay['email'].str.lower().str.strip()
df_active_pay = df_active_pay[~df_active_pay['email'].str.contains(' ', na=False)]
df_active_pay = df_active_pay.reset_index(drop=True)
print(len(df_active_pay))

111

In [90]:
df_active_pay[['username', 'domain']] = df_active_pay['email'].str.split('@', expand=True)
#df_active_pay = df_active_pay.drop_duplicates(subset='domain')
df_active_pay.head(2)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep,username,domain
0,6g7t1ct1@dyqbmail.com,Essential-Plan-Monthly-USD-Monthly,Active,457.23,0.0,457.23,61,0,0.0,0.0,0.0,0,0,6g7t1ct1,dyqbmail.com
1,a.samoilov@youtalk.international,Essential-Plan-Monthly-USD-Monthly,Active,432.00,0.0,432.00,1,0,36.0,0.0,36.0,1,0,a.samoilov,youtalk.international

In [91]:
final_df = df_active_pay[['email', 'domain']]
final_df

                                email                      domain
0               6g7t1ct1@dyqbmail.com                dyqbmail.com
1    a.samoilov@youtalk.international       youtalk.international
2                  abijith@edbrig.com                  edbrig.com
3                 abir@upcounting.com              upcounting.com
4                 admin@brefni.com.au               brefni.com.au
..                                ...                         ...
106             tooba@creatifsoft.com             creatifsoft.com
107      tyler@epicestateservices.com      epicestateservices.com
108             vhcn1tck@dyqbmail.com                dyqbmail.com
109           vic@veesionaustralia.io         veesionaustralia.io
110    www@abanicosairedistintosl.com  abanicosairedistintosl.com

[111 rows x 2 columns]

In [92]:
final_df.to_csv('enterprise_domain(active_pay_400_550).csv', index = False)

In [93]:
final = pd.merge(df_active_pay, df2, on = ['domain','email'], how = 'left')
print(len(final))
final.head(5)

111

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,...,username,domain,category,company_size,email_provider,confidence,other_industry_category,website,website_status,website_reason
0,6g7t1ct1@dyqbmail.com,Essential-Plan-Monthly-USD-Monthly,Active,457.23,0.0,457.23,61,0,0.0,0.0,...,6g7t1ct1,dyqbmail.com,Other,solo,Yes,95,Email Service Provider,unreachable,unreachable,Connection Error
1,a.samoilov@youtalk.international,Essential-Plan-Monthly-USD-Monthly,Active,432.00,0.0,432.00,1,0,36.0,0.0,...,a.samoilov,youtalk.international,Professional Services,50 to 100,No,95,NaN,much_info,reachable,200
2,abijith@edbrig.com,Essential-Plan-Monthly-USD-Monthly,Active,465.00,0.0,465.00,2,0,30.0,0.0,...,abijith,edbrig.com,Professional Services,1 to 5,No,50,NaN,unreachable,unreachable,SSL Error
3,abir@upcounting.com,Essential-Plan-Monthly-USD-Monthly,Active,500.64,0.0,500.64,1,1,40.0,0.0,...,abir,upcounting.com,Professional Services,5 to 20,No,95,NaN,much_info,reachable,200
4,admin@brefni.com.au,Essential-Plan-Yearly-USD-Yearly,Active,443.00,0.0,443.00,1,0,19.0,0.0,...,admin,brefni.com.au,Professional Services,50 to 100,No,95,Civil Engineering and Infrastructure,much_info,reachable,200

In [ ]:
final = final.to_csv('active_pay_400_550_domain_classify.csv', index = False)