In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('Enterprise Clients.csv')
df2 = pd.read_csv('enterprise_domain(active_pay_900)_enriched.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [15]:
print(df['email'].nunique())

5243

In [16]:
df_active = df[df['subscription_status'] == 'Active']
print(len(df_active))

1780

In [17]:
df_active['Pay'].dtypes

dtype('float64')

In [18]:
df_active_pay = df_active[df_active['Pay']>900]
print(len(df_active_pay))

107

In [19]:
df_active_pay = df_active_pay.copy()
df_active_pay['email'] = df_active_pay['email'].str.lower().str.strip()
df_active_pay = df_active_pay[~df_active_pay['email'].str.contains(' ', na=False)]
df_active_pay = df_active_pay.reset_index(drop=True)
print(len(df_active_pay))

107

In [20]:
df_active_pay[['username', 'domain']] = df_active_pay['email'].str.split('@', expand=True)
df_active_pay = df_active_pay.drop_duplicates(subset='domain')
df_active_pay.head(2)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep,username,domain
0,abhishek@infinitesolutionedu.com,Standard-Plan-Monthly-USD-Monthly,Active,948.73,150.66,798.07,8,12,495.87,150.66,345.21,6,10,abhishek,infinitesolutionedu.com
1,accounts@buildtechnics.com.au,Essential-Plan-Monthly-USD-Monthly,Active,1210.18,0.00,1210.18,1,2,38.00,0.00,38.00,1,0,accounts,buildtechnics.com.au

In [21]:
final_df = df_active_pay[['email', 'domain']]
final_df

                                     email                        domain
0         abhishek@infinitesolutionedu.com       infinitesolutionedu.com
1            accounts@buildtechnics.com.au          buildtechnics.com.au
2    accounts@premiumplusproperties.com.au  premiumplusproperties.com.au
3                      accounts@specfx.com                    specfx.com
4                   admin@andromarkets.com              andromarkets.com
..                                     ...                           ...
102                      viktor@eliptis.se                    eliptis.se
103                          wloo@msxi.com                      msxi.com
104              xander.f@retailinsight.io              retailinsight.io
105                           yash@xebo.ai                       xebo.ai
106                       ziv.m@lsports.eu                    lsports.eu

[107 rows x 2 columns]

In [22]:
final_df.to_csv('enterprise_domain(active_pay_900).csv', index = False)

In [23]:
final = pd.merge(df_active_pay, df2, on = ['domain','email'], how = 'left')
print(len(final))
final.head(5)

107

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,...,username,domain,category,company_size,email_provider,confidence,other_industry_category,website,website_status,website_reason
0,abhishek@infinitesolutionedu.com,Standard-Plan-Monthly-USD-Monthly,Active,948.73,150.66,798.07,8,12,495.87,150.66,...,abhishek,infinitesolutionedu.com,Education and e-learning,5 to 20,No,70,NaN,little_info,reachable,200
1,accounts@buildtechnics.com.au,Essential-Plan-Monthly-USD-Monthly,Active,1210.18,0.00,1210.18,1,2,38.00,0.00,...,accounts,buildtechnics.com.au,Professional Services,1 to 5,No,50,NaN,unreachable,unreachable,403
2,accounts@premiumplusproperties.com.au,Essential-Plan-Monthly-USD-Monthly,Active,1671.00,0.00,1671.00,3,0,321.00,0.00,...,accounts,premiumplusproperties.com.au,Real Estate and Property Management,1 to 5,No,95,NaN,much_info,reachable,200
3,accounts@specfx.com,Essential-Plan-Monthly-USD-Monthly,Active,1844.81,16.00,1828.81,6,9,394.74,0.00,...,accounts,specfx.com,Financial Service,50 to 100,No,95,NaN,much_info,reachable,200
4,admin@andromarkets.com,Standard-Plan-Monthly-USD-Monthly,Active,1071.29,0.00,1071.29,2,2,130.00,0.00,...,admin,andromarkets.com,Financial Service,50 to 100,No,95,NaN,much_info,reachable,200

In [24]:
final = final.to_csv('active_pay_900_domain_classify.csv', index = False)