In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('Enterprise Clients.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [26]:
df_active = df[df['subscription_status'] == 'Active']
print(len(df_active))

1780

In [27]:
df_active['Pay'].dtypes

dtype('float64')

In [30]:
df_active_pay = df_active[df_active['Pay_Sep']>100]
print(len(df_active_pay))
df_active_pay

137

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
52,abdyl_shkodra@urbantouchinterior.com,Essential-Plan-Monthly-USD-Monthly,Active,586.65,0.00,586.65,10,4,190.00,0.00,190.00,7,0
55,abhishek@infinitesolutionedu.com,Standard-Plan-Monthly-USD-Monthly,Active,948.73,150.66,798.07,8,12,495.87,150.66,345.21,6,10
90,accounts@premiumplusproperties.com.au,Essential-Plan-Monthly-USD-Monthly,Active,1671.00,0.00,1671.00,3,0,321.00,0.00,321.00,2,0
97,accounts@specfx.com,Essential-Plan-Monthly-USD-Monthly,Active,1844.81,16.00,1828.81,6,9,394.74,0.00,394.74,5,1
141,admin@andromarkets.com,Standard-Plan-Monthly-USD-Monthly,Active,1071.29,0.00,1071.29,2,2,130.00,0.00,130.00,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,vm@sialico.com,Essential-Plan-Yearly-USD-Yearly,Active,154.00,0.00,154.00,1,0,144.00,0.00,144.00,1,0
5149,wilma+verbal@salesys.se,Essential-Plan-Monthly-USD-Monthly,Active,717.31,0.00,717.31,62,0,138.10,0.00,138.10,32,0
5153,wloo@msxi.com,Essential-Plan-Monthly-USD-Monthly,Active,1895.50,0.00,1895.50,1,1,125.00,0.00,125.00,1,0
5164,xander.f@retailinsight.io,Essential-Plan-Monthly-USD-Monthly,Active,1573.13,0.00,1573.13,22,0,137.00,0.00,137.00,22,0
5187,yash@xebo.ai,Essential-Plan-Monthly-USD-Monthly,Active,2073.42,0.00,2073.42,8,4,271.50,0.00,271.50,4,0