In [61]:
import pandas as pd

In [62]:
df = pd.read_csv('Enterprise Clients.csv')
df2 = pd.read_csv('enterprise_domain(active_pay_500_900)_enriched.csv')
print(df.shape)
df.head(2)

(5243, 13)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep
0,0.0@hrops.co.uk,NaN,Cancelled,15.0,0.0,15.0,0,0,0.0,0.0,0.0,0,0
1,06407lgd@dudscuapcut.store,Essential-Plan-Monthly-USD-Monthly,Cancelled,20.0,0.0,20.0,1,0,0.0,0.0,0.0,0,0

In [63]:
print(df['email'].nunique())

5243

In [64]:
df_active = df[df['subscription_status'] == 'Active']
print(len(df_active))

1780

In [65]:
df_active['Pay'].dtypes

dtype('float64')

In [66]:
df_active_pay = df_active[df_active['Pay'].between(500,900)]
print(len(df_active_pay))

100

In [67]:
df_active_pay = df_active_pay.copy()
df_active_pay['email'] = df_active_pay['email'].str.lower().str.strip()
df_active_pay = df_active_pay[~df_active_pay['email'].str.contains(' ', na=False)]
df_active_pay = df_active_pay.reset_index(drop=True)
print(len(df_active_pay))

100

In [68]:
df_active_pay[['username', 'domain']] = df_active_pay['email'].str.split('@', expand=True)
df_active_pay = df_active_pay.drop_duplicates(subset='domain')
df_active_pay.head(2)

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,Net_Sep,phone_count_Sep,agent_count_Sep,username,domain
0,abdyl_shkodra@urbantouchinterior.com,Essential-Plan-Monthly-USD-Monthly,Active,586.65,0.0,586.65,10,4,190.0,0.0,190.0,7,0,abdyl_shkodra,urbantouchinterior.com
1,abir@upcounting.com,Essential-Plan-Monthly-USD-Monthly,Active,500.64,0.0,500.64,1,1,40.0,0.0,40.0,1,0,abir,upcounting.com

In [69]:
final_df = df_active_pay[['email', 'domain']]
final_df

                                   email                   domain
0   abdyl_shkodra@urbantouchinterior.com   urbantouchinterior.com
1                    abir@upcounting.com           upcounting.com
2                  admin@aaqibonline.com          aaqibonline.com
3                 admin@infin8source.com         infin8source.com
4          admin@navilinx-telematics.com  navilinx-telematics.com
..                                   ...                      ...
95            tamer.elsherif@si-ware.com              si-ware.com
96            technical@regulusprime.com         regulusprime.com
97     tye.robinson@crestflowdigital.com     crestflowdigital.com
98          tyler@epicestateservices.com   epicestateservices.com
99               wilma+verbal@salesys.se               salesys.se

[100 rows x 2 columns]

In [70]:
final_df.to_csv('enterprise_domain(active_pay)_500_900).csv', index = False)

In [71]:
final = pd.merge(df_active_pay, df2, on = ['domain','email'], how = 'left')
print(len(final))
final.head(5)

100

,email,initial_subscription,subscription_status,Pay,Refund,Net,phone_count,agent_count,Pay_Sep,Refund_Sep,...,username,domain,category,company_size,email_provider,confidence,other_industry_category,website,website_status,website_reason
0,abdyl_shkodra@urbantouchinterior.com,Essential-Plan-Monthly-USD-Monthly,Active,586.65,0.0,586.65,10,4,190.0,0.0,...,abdyl_shkodra,urbantouchinterior.com,Other,solo,No,50,Interior Design,no_info,reachable,200
1,abir@upcounting.com,Essential-Plan-Monthly-USD-Monthly,Active,500.64,0.0,500.64,1,1,40.0,0.0,...,abir,upcounting.com,Professional Services,5 to 20,No,95,NaN,much_info,reachable,200
2,admin@aaqibonline.com,Essential,Active,761.30,0.0,761.30,54,0,0.0,0.0,...,admin,aaqibonline.com,Marketing and Advertising,1 to 5,No,95,NaN,much_info,reachable,200
3,admin@infin8source.com,Essential-Plan-Monthly-USD-Monthly,Active,677.00,0.0,677.00,5,0,21.0,0.0,...,admin,infin8source.com,Professional Services,50 to 100,No,95,NaN,much_info,reachable,200
4,admin@navilinx-telematics.com,Essential-Plan-Monthly-USD-Monthly,Active,562.25,0.0,562.25,5,1,41.0,0.0,...,admin,navilinx-telematics.com,Technology and Software Development,50 to 100,No,95,NaN,much_info,reachable,200

In [72]:
final = final.to_csv('active_pay_500_900_domain_classify.csv', index = False)