In [230]:
import pandas as pd
import numpy as np

In [231]:
deal1 = pd.read_csv('deals-19264736-555.csv')
deal2 = pd.read_csv('deals-19264736-556.csv')
bd = pd.read_csv('busines_domains_ac.csv')

In [232]:
deal1.head(2)

,Person - Email - Work,Person - Email - Home,Person - Email - Other,Person - Country,Person - Phone - Work,Person - Phone - Home,Person - Phone - Mobile,Person - Phone - Other
0,NaN,NaN,th@watchretailgroup.com,United Kingdom,NaN,NaN,NaN,'+447385577652
1,NaN,NaN,exilant1@posteo.de,Switzerland,NaN,NaN,NaN,'+41793379624

In [233]:
deal1["email"] = deal1["Person - Email - Other"].fillna(deal1["Person - Email - Work"])
deal1 = deal1[["email"]]
print(len(deal1))
deal1.head(2)

3564

                     email
0  th@watchretailgroup.com
1       exilant1@posteo.de

In [234]:
deal1 = deal1.copy()  

deal1['email'] = deal1['email'].str.split(r'[;, ]+')
deal1 = deal1.explode('email').reset_index(drop=True)
deal1['email'] = deal1['email'].str.strip()
deal1 = deal1[deal1['email'].notna() & (deal1['email'] != '')]
deal1 = deal1.sort_values(by='email', ascending=False)

print(len(deal1))
deal1.head(2)

3588

                               email
2768   zyderagullana@salevolume.info
2220  zubairel@northernscapeco.co.uk

In [235]:
deal1 = deal1.drop_duplicates()
print(len(deal1))
deal1.head(2)

3549

                               email
2768   zyderagullana@salevolume.info
2220  zubairel@northernscapeco.co.uk

In [236]:
deal2.head(2)

,Deal - Title,Person - Country,Deal - Deal created,Person - Phone - Work,Person - Phone - Home,Person - Phone - Mobile,Person - Phone - Other,Deal - Contact person,Deal - Owner,Deal - Status,Deal - Pipeline,Deal - Last email sent,Deal - Label
0,mccall@leadossystems.com,United States,2025-10-30 23:33:26,NaN,NaN,NaN,'+15033497962,McCall Delaney,Rachhya Sherchan,Won,Converted Business - Customer Success,2025-10-31 21:32:07,"Business, BUSINESSS EMAIL, Business Both"
1,meleksevim@houkika.com,Turkey,2025-10-30 22:56:53,NaN,NaN,NaN,'+905384756885,Melek Sevim,Riya,Won,Converted Business - Customer Success,2025-10-31 12:53:16,"BUSINESS CALL, BUSINESSS EMAIL"

In [237]:
deal2 = deal2.rename(columns={
    'Deal - Title': 'email'
})
deal2 = deal2[['email']]
print(len(deal2))
deal2.head(2)

1318

                      email
0  mccall@leadossystems.com
1    meleksevim@houkika.com

In [238]:
deal2 = deal2.drop_duplicates()
print(len(deal2))
deal2.head(2)

1303

                      email
0  mccall@leadossystems.com
1    meleksevim@houkika.com

In [239]:
bd.head(2)

,distinct_id,$distinct_id_before_identity
0,$device:76a19949-bdf6-4afc-a015-ce8420d2e71f,ashton@roilift.com
1,$device:194dec5a07a4b2-05f233d445bda-1d525636-...,emily@bmco.com.au

In [240]:
bd['email'] = np.where(
    bd['$distinct_id_before_identity'].str.contains('@', na=False),
    bd['$distinct_id_before_identity'],
    np.where(
        bd['distinct_id'].str.contains('@', na=False),
        bd['distinct_id'],
        np.nan  # set NaN if no '@' in either
    )
)
print(len(bd))
bd.head(2)

4301

,distinct_id,$distinct_id_before_identity,email
0,$device:76a19949-bdf6-4afc-a015-ce8420d2e71f,ashton@roilift.com,ashton@roilift.com
1,$device:194dec5a07a4b2-05f233d445bda-1d525636-...,emily@bmco.com.au,emily@bmco.com.au

In [241]:
bd = bd[['email']]
bd = bd.drop_duplicates()
print(len(bd))
bd.head(2)

4223

                email
0  ashton@roilift.com
1   emily@bmco.com.au

In [242]:
deal_combined = pd.merge(deal1, deal2, on = 'email', how = 'outer')
print(len(deal_combined))
deal_bd_combined = pd.merge(deal_combined, bd, on = 'email', how = 'outer')
print(len(deal_bd_combined))
deal_bd_combined.head(2)

4830
4873

                        email
0             0.0@hrops.co.uk
1  06407lgd@dudscuapcut.store

In [243]:
deal_combined['email'] = deal_combined['email'].str.lower().str.strip()
deal_combined = deal_combined[~deal_combined['email'].str.contains(' ', na=False)]
deal_combined = deal_combined.reset_index(drop=True)
print(len(deal_combined))
deal_combined.to_csv('deal.csv', index = False)

4822